build:
  system_packages:
    - python3.11
    - python3.11-venv
  python_version: "3.11"
  python_packages:
    - "gradio>=4.19.2"
    - "sqlalchemy>=2.0.0"
    - "google-generativeai>=0.3.0"
    - "langchain>=0.1.0"
    - "python-dotenv>=1.0.0"

runtime:
  env:
    - PYTHON_PATH=/home/user/app