build:
  system_packages:
    - python3.11
    - python3.11-venv
  python_version: "3.11"
  python_packages:
    - "pandas==2.2.3"
    - "numpy==1.26.4"
    - "python-dotenv==1.0.1"
    - "gradio==5.22.0"
    - "google-generativeai==0.8.3"
    - "pydantic==2.10.6"
    - "sqlalchemy"
    - "alembic"
    - "huggingface-hub==0.29.3"
    - "regex"

runtime:
  env:
    - PYTHON_PATH=/app
    - HF_SPACE=true