# .github/workflows/ci.yml
name: Python CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create virtual environment
      run: python -m venv .venv

    - name: Install uv
      run: |
        source .venv/bin/activate
        pip install uv

    - name: Install dependencies
      run: |
        source .venv/bin/activate
        uv pip install -r requirements.txt

    - name: Create .env file for tests
      run: |
        echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> .env
        echo "DATABASE_URL=sqlite:///./chatbot_ci_test.db" >> .env

    - name: Run tests
      run: |
        source .venv/bin/activate
        export PYTHONPATH=${{ github.workspace }}
        pytest -v
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

  deploy-to-hf-space:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create virtual environment
      run: python -m venv .venv

      - name: Install uv and Hugging Face Hub library
        run: |
          source .venv/bin/activate
          pip install uv
          uv pip install huggingface-hub

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git remote add space https://MoeTensors:$HF_TOKEN@huggingface.co/spaces/MoeTensors/E-commerce_chatbot
          git push --force space main
