name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0  # This ensures a full clone, not a shallow one
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install uv
          # Install numpy first to avoid compatibility issues
          uv pip install --system numpy==1.26.4
          # Install core dependencies with specific versions
          uv pip install --system python-dotenv==1.0.1 langchain==0.3.0 langchain-core==0.3.46 langgraph==0.3.14 langchain-openai==0.3.9 langchain-google-genai==2.1.0 google-ai-generativelanguage==0.6.17 pytest==7.4.0 gradio==5.22.0 huggingface-hub==0.29.3
          # Install pandas last
          uv pip install --system pandas==2.2.3
          # Install any remaining dependencies
          uv pip install --system -r requirements.txt
      - name: Run tests
        run: |
          pytest tests/
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

  deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0  # Add this to ensure a full clone
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add space https://MoeTensors:$HF_TOKEN@huggingface.co/spaces/MoeTensors/E-commerce_chatbot
          git push --force space main