name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0  # This ensures a full clone, not a shallow one
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install uv
      - name: Install dependencies
        run: |
          source venv/bin/activate
          # Install numpy first to avoid compatibility issues
          uv pip install numpy==1.26.4
          # Install core dependencies with specific versions
          uv pip install python-dotenv==1.0.1 langchain==0.3.21 langchain-core==0.3.47 langgraph==0.3.18 langchain-openai==0.3.9 langchain-google-genai==2.0.10 google-ai-generativelanguage==0.6.10 pytest==7.4.0 gradio==5.22.0 huggingface-hub==0.29.3 google-generativeai==0.8.3
          # Install ChromaDB and its dependencies
          uv pip install chromadb==0.6.3 pydantic==2.10.6 hnswlib==0.8.0 sentence-transformers==3.4.1
          # Install pandas last
          uv pip install pandas==2.2.3
          # Install any remaining dependencies
          uv pip install -r requirements.txt
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest tests/
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

  deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install uv
      - name: Install dependencies
        run: |
          source venv/bin/activate
          uv pip install -r requirements.txt
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          source venv/bin/activate
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add space https://MoeTensors:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/MoeTensors/E-commerce_chatbot
          git push --force space main